dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "shashank-ssriva-github"

services:
  - docker

language: python

script:
  - python3 -m pytest -v

  # code coverage test  
  - coverage report -m app.py



after_success:
  - sh .deploy_scripts/deploy_dockerhub.sh
    test "$TRAVIS_BRANCH" = "master" && sh .deploy_scripts/deploy_heroku.sh