sudo: required

services:
  - docker

language: python

script:
  - hostname

after_success:
  - sh .deploy_scripts/deploy_dockerhub.sh
    test "$TRAVIS_BRANCH" = "master" && sh .deploy_scripts/deploy_heroku.sh