sudo: required

services:
  - docker

language: python3.7.5

script:
#  - python -m pytest -v

after_success:
  - sh .deploy_scripts/deploy_dockerhub.sh
    test "$TRAVIS_BRANCH" = "master" && sh .deploy_scripts/deploy_heroku.sh